/**
 * @file tpl_ioc_api_config.h
 *
 * @section desc File description
 *
 * OS data structure generated from application only_one_periodic_task
 * Automatically generated by goil on Sun Dec 13 17:02:07 2015
 * from root OIL file periodic.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the Lesser GNU Public Licence
 *
 * @section infos File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include "tpl_app_config.h"

#include "tpl_os_internal_types.h"
#include "tpl_ioc.h"
#include "ioc_types.h"

#define API_START_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of IOC APIs
 */


#define API_STOP_SEC_CODE
#include "tpl_memmap.h" 

/* End of file tpl_ioc_api_config.h */
