/**
 * @file tpl_os.c
 *
 * @section File description
 *
 * This file gathers system call declarations.
 *
 * Generated from application only_one_periodic_task
 * Automatically generated by goil on Sun Dec 13 17:02:07 2015
 * from root OIL file periodic.oil
 *
 * @section File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include "tpl_os.h"
#include "tpl_control.h"

#include "tpl_os_os_kernel.h"
#include "tpl_os_os.h"
#include "tpl_os_interrupt_kernel.h"
#include "tpl_os_task_kernel.h"
#include "tpl_os_resource_kernel.h"
#include "tpl_os_alarm_kernel.h"

/*--------------------------------------------------------------------------*
 * os system calls.
 * corresponding kernel implementation is in files
 * tpl_os_os_kernel.h and tpl_os_os_kernel.c
 * tpl_os_os.h and tpl_os_os.c
 *--------------------------------------------------------------------------*/

/*
 * GetActiveApplicationMode
 *
 * This service returns the current application mode. It may be used to
 * write mode dependent code.
 *
 *
 * Return value:
 * The active application mode
 */
FUNC(AppModeType, OS_CODE) GetActiveApplicationMode(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_GetActiveApplicationMode);

  AppModeType res = tpl_get_active_application_mode_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_GetActiveApplicationMode);
  
  
  return res;
  
}

/*
 * tpl_start_os
 *
 * The user can call this system service to start the operating system in
 * a specific mode.
 *
 * Note: StartOS is provided in tpl_os_os.c.
 *       StartOS calls tpl_start_os.
 *       tpl_start_os should not be called directly by the application
 *
 * mode:  The application mode
 */
FUNC(void, OS_CODE) tpl_start_os(CONST(AppModeType, AUTOMATIC) mode)
{
  
  slow_task( (void*) &mode,NULL,NULL,OSServiceId_StartOS);
tpl_start_os_service(mode);

  compute_NEFT( (void*) &mode,NULL,NULL,OSServiceId_StartOS);
  
  
}

/*
 * ShutdownOS
 *
 * The user can call this system service to abort the overall system (e.g.
 * emergency off). The operating system also calls this function
 * internally, if it has reached an undefined internal state and is no
 * longer ready to run.
 *
 * error:  The error that occured
 */
FUNC(void, OS_CODE) ShutdownOS(CONST(StatusType, AUTOMATIC) error)
{
  
  slow_task( (void*) &error,NULL,NULL,OSServiceId_ShutdownOS);
tpl_shutdown_os_service(error);

  compute_NEFT( (void*) &error,NULL,NULL,OSServiceId_ShutdownOS);
  
  
}

/*--------------------------------------------------------------------------*
 * interrupt system calls.
 * corresponding kernel implementation is in files
 * tpl_os_interrupt_kernel.h and tpl_os_interrupt_kernel.c
 *--------------------------------------------------------------------------*/

/*
 * EnableAllInterrupts
 *
 * This service restores the state saved by DisableAllInterrupts.
 *
 */
FUNC(void, OS_CODE) EnableAllInterrupts(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_EnableAllInterrupts);
tpl_enable_all_interrupts_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_EnableAllInterrupts);
  
  
}

/*
 * DisableAllInterrupts
 *
 * This service disables all interrupts for which the hardware supports
 * disabling. The state before is saved for the EnableAllInterrupts call.
 *
 */
FUNC(void, OS_CODE) DisableAllInterrupts(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_DisableAllInterrupts);
tpl_disable_all_interrupts_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_DisableAllInterrupts);
  
  
}

/*
 * ResumeAllInterrupts
 *
 * This service restores the recognition status of all interrupts saved by
 * the SuspendAllInterrupts service.
 *
 */
FUNC(void, OS_CODE) ResumeAllInterrupts(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_ResumeAllInterrupts);
tpl_resume_all_interrupts_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_ResumeAllInterrupts);
  
  
}

/*
 * SuspendAllInterrupts
 *
 * This service saves the recognition status of all interrupts and
 * disables all interrupts for which the hardware supports disabling.
 *
 */
FUNC(void, OS_CODE) SuspendAllInterrupts(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_SuspendAllInterrupts);
tpl_suspend_all_interrupts_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_SuspendAllInterrupts);
  
  
}

/*
 * ResumeOSInterrupts
 *
 * This service restores the recognition status of interrupts saved by the
 * SuspendOSInterrupts service.
 *
 */
FUNC(void, OS_CODE) ResumeOSInterrupts(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_ResumeOSInterrupts);
tpl_resume_os_interrupts_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_ResumeOSInterrupts);
  
  
}

/*
 * SuspendOSInterrupts
 *
 * This service saves the recognition status of interrupts of category 2
 * and disables the recognition of these interrupts.
 *
 */
FUNC(void, OS_CODE) SuspendOSInterrupts(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_SuspendOSInterrupts);
tpl_suspend_os_interrupts_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_SuspendOSInterrupts);
  
  
}

/*
 * CallTerminateISR2
 *
 * 
 *
 */
FUNC(void, OS_CODE) CallTerminateISR2(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_CallTerminateISR2);
tpl_call_terminate_isr2_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_CallTerminateISR2);
  
  
}

/*--------------------------------------------------------------------------*
 * task system calls.
 * corresponding kernel implementation is in files
 * tpl_os_task_kernel.h and tpl_os_task_kernel.c
 *--------------------------------------------------------------------------*/

/*
 * ActivateTask
 *
 * Activate a task
 *
 * task_id:  The identifier of the task to activate
 *
 * Return value:
 * E_OK:       No error (Standard & Extended)
 * E_OS_LIMIT: Too many activations of <task_id> (Standard & Extended)
 * E_OS_ID:    <task_id> is invalid (Extended)
 */
FUNC(StatusType, OS_CODE) ActivateTask(CONST(TaskType, AUTOMATIC) task_id)
{
  
  slow_task( (void*) &task_id,NULL,NULL,OSServiceId_ActivateTask);

  StatusType res = tpl_activate_task_service(task_id);

  compute_NEFT( (void*) &task_id,NULL,NULL,OSServiceId_ActivateTask);
  
  
  return res;
  
}

/*
 * TerminateTask
 *
 * Terminate the calling task
 *
 *
 * Return value:
 * E_OS_RESOURCE: The calling task still occupies a resource (Extended)
 * E_OS_CALLEVEL: Call at interrupt level (Extended)
 */
FUNC(StatusType, OS_CODE) TerminateTask(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_TerminateTask);

  StatusType res = tpl_terminate_task_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_TerminateTask);
  
  
  return res;
  
}

/*
 * ChainTask
 *
 * Terminate the calling task and activate task task_id
 *
 * task_id:  The identifier of the task to chain to
 *
 * Return value:
 * E_OS_LIMIT:    Too many activations of <task_id> (Standard & Extended)
 * E_OS_ID:       <task_id> is invalid (Extended)
 * E_OS_RESOURCE: The calling task still occupies a resource (Extended)
 * E_OS_CALLEVEL: Call at interrupt level (Extended)
 */
FUNC(StatusType, OS_CODE) ChainTask(CONST(TaskType, AUTOMATIC) task_id)
{
  
  slow_task( (void*) &task_id,NULL,NULL,OSServiceId_ChainTask);

  StatusType res = tpl_chain_task_service(task_id);

  compute_NEFT( (void*) &task_id,NULL,NULL,OSServiceId_ChainTask);
  
  
  return res;
  
}

/*
 * Schedule
 *
 * Call the scheduler
 *
 *
 * Return value:
 * E_OK:          No error (Standard & Extended)
 * E_OS_RESOURCE: The calling task still occupies a resource (Extended)
 * E_OS_CALLEVEL: Call at interrupt level (Extended)
 */
FUNC(StatusType, OS_CODE) Schedule(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_Schedule);

  StatusType res = tpl_schedule_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_Schedule);
  
  
  return res;
  
}

/*
 * GetTaskID
 *
 * Get the id of the calling task
 *
 * task_id:  A pointer to the var where the identifier of the task will be
 *           stored
 *
 * Return value:
 * E_OK: No error (Standard & Extended)
 */
FUNC(StatusType, OS_CODE) GetTaskID(VAR(TaskRefType, AUTOMATIC) task_id)
{
  
  slow_task( (void*) &task_id,NULL,NULL,OSServiceId_GetTaskID);

  StatusType res = tpl_get_task_id_service(task_id);

  compute_NEFT( (void*) &task_id,NULL,NULL,OSServiceId_GetTaskID);
  
  
  return res;
  
}

/*
 * GetTaskState
 *
 * Get the task state of a task
 *
 * task_id:  The identifier of the task
 * state:  A pointer to the var where the state of the task will be stored
 *
 * Return value:
 * E_OK:        No error (Standard & Extended)
 * E_OS_ID:     <alarm_id> is invalid (Extended)
 */
FUNC(StatusType, OS_CODE) GetTaskState(CONST(TaskType, AUTOMATIC) task_id,VAR(TaskStateRefType, AUTOMATIC) state)
{
  
  slow_task( (void*) &task_id, (void*) &state,NULL,OSServiceId_GetTaskState);

  StatusType res = tpl_get_task_state_service(task_id, state);

  compute_NEFT( (void*) &task_id, (void*) &state,NULL,OSServiceId_GetTaskState);
  
  
  return res;
  
}

/*
 * CallTerminateTask
 *
 * Used internally as return address of tasks, should not be called by the
 * user
 *
 */
FUNC(void, OS_CODE) CallTerminateTask(void)
{
  
  slow_task(NULL,NULL,NULL,OSServiceId_CallTerminateTask);
tpl_call_terminate_task_service();

  compute_NEFT(NULL,NULL,NULL,OSServiceId_CallTerminateTask);
  
  
}

/*--------------------------------------------------------------------------*
 * resource system calls.
 * corresponding kernel implementation is in files
 * tpl_os_resource_kernel.h and tpl_os_resource_kernel.c
 *--------------------------------------------------------------------------*/

/*
 * GetResource
 *
 * Get resource res_id. As a result, the priority of the caller may be
 * raised to the priority of the resource if the latter is higher
 *
 * res_id:  The id of the resource to get.
 *
 * Return value:
 * E_OK:    No error (Standard & Extended)
 * E_OS_ID: <res_id> is invalid (Extended)
 */
FUNC(StatusType, OS_CODE) GetResource(CONST(ResourceType, AUTOMATIC) res_id)
{
  
  slow_task( (void*) &res_id,NULL,NULL,OSServiceId_GetResource);

  StatusType res = tpl_get_resource_service(res_id);

  compute_NEFT( (void*) &res_id,NULL,NULL,OSServiceId_GetResource);
  
  
  return res;
  
}

/*
 * ReleaseResource
 *
 * Release resource res_id. The priority of the caller returns to the
 * priority it had before getting the resource
 *
 * res_id:  The id of the resource to release.
 *
 * Return value:
 * E_OK:        No error (Standard & Extended)
 * E_OS_ID:     <res_id> is invalid (Extended)
 * E_OS_ACCESS: Attempt to get a resource which is already occupied by any
 *     task or ISR, or the statically assigned priority of the calling
 *     task or interrupt routine is higher than the calculated ceiling
 *     priority (Extended)
 */
FUNC(StatusType, OS_CODE) ReleaseResource(CONST(ResourceType, AUTOMATIC) res_id)
{
  
  slow_task( (void*) &res_id,NULL,NULL,OSServiceId_ReleaseResource);

  StatusType res = tpl_release_resource_service(res_id);

  compute_NEFT( (void*) &res_id,NULL,NULL,OSServiceId_ReleaseResource);
  
  
  return res;
  
}

/*--------------------------------------------------------------------------*
 * alarm system calls.
 * corresponding kernel implementation is in files
 * tpl_os_alarm_kernel.h and tpl_os_alarm_kernel.c
 *--------------------------------------------------------------------------*/

/*
 * GetAlarmBase
 *
 * Get information about the underlying counter.
 * See page 63 of the OSEK OS 2.2.3 specification.
 *
 * alarm_id:  The identifier of the alarm
 * info:  A pointer to the AlarmBaseType data where the informations will
 *        be stored
 *
 * Return value:
 * E_OK:    No error (Standard & Extended)
 * E_OS_ID: <alarm_id> is invalid (Extended)
 */
FUNC(StatusType, OS_CODE) GetAlarmBase(CONST(AlarmType, AUTOMATIC) alarm_id,VAR(AlarmBaseRefType, AUTOMATIC) info)
{
  
  slow_task( (void*) &alarm_id, (void*) &info,NULL,OSServiceId_GetAlarmBase);

  StatusType res = tpl_get_alarm_base_service(alarm_id, info);

  compute_NEFT( (void*) &alarm_id, (void*) &info,NULL,OSServiceId_GetAlarmBase);
  
  
  return res;
  
}

/*
 * GetAlarm
 *
 * Get the remaining number of ticks before the alarm expire.
 * See page 63 of the OSEK OS 2.2.3 specification.
 *
 * alarm_id:  The identifier of the alarm
 * tick:  A pointer to the TickType data where the remaining number of
 *        ticks before the alarm expire will be stored
 *
 * Return value:
 * E_OK:        No error (Standard & Extended)
 * E_OS_NOFUNC: Alarm <alarm_id> is not in use (Standard & Extended)
 * E_OS_ID:     <alarm_id> is invalid (Extended)
 */
FUNC(StatusType, OS_CODE) GetAlarm(CONST(AlarmType, AUTOMATIC) alarm_id,VAR(TickRefType, AUTOMATIC) tick)
{
  
  slow_task( (void*) &alarm_id, (void*) &tick,NULL,OSServiceId_GetAlarm);

  StatusType res = tpl_get_alarm_service(alarm_id, tick);

  compute_NEFT( (void*) &alarm_id, (void*) &tick,NULL,OSServiceId_GetAlarm);
  
  
  return res;
  
}

/*
 * SetRelAlarm
 *
 * SetRelAlarm starts alarm <alarm_id>. After <increment> ticks have
 * elapsed, the task assigned to the alarm <alarm_id> is activated or the
 * assigned event (only for extended tasks) is set or the alarm-callback
 * routine is called.
 * See page 63 of the OSEK OS 2.2.3 specification.
 *
 * alarm_id:  The identifier of the alarm
 * increment:  Relative value in ticks.
 * cycle:  Cycle value in case of a cyclic alarm. In case of a one shot
 *         alarm, cycle shall be zero
 *
 * Return value:
 * E_OK:        No error (Standard & Extended)
 * E_OS_NOFUNC: Alarm <alarm_id> is already in use (Standard & Extended)
 * E_OS_ID:     <alarm_id> is invalid (Extended)
 * E_OS_VALUE:  <increment> out of bounds (Extended)
 * E_OS_VALUE:  <cycle> out of bounds (Extended)
 */
FUNC(StatusType, OS_CODE) SetRelAlarm(CONST(AlarmType, AUTOMATIC) alarm_id,CONST(TickType, AUTOMATIC) increment,CONST(TickType, AUTOMATIC) cycle)
{
  
  slow_task( (void*) &alarm_id, (void*) &increment, (void*) &cycle,OSServiceId_SetRelAlarm);

  StatusType res = tpl_set_rel_alarm_service(alarm_id, increment, cycle);

  compute_NEFT( (void*) &alarm_id, (void*) &increment, (void*) &cycle,OSServiceId_SetRelAlarm);
  
  
  return res;
  
}

/*
 * SetAbsAlarm
 *
 * SetAbsAlarm starts alarm <alarm_id>. At <start> ticks, the task
 * assigned to the alarm <alarm_id> is activated or the assigned event
 * (only for extended tasks) is set or the alarm-callback routine is
 * called.
 * See page 64 of the OSEK OS 2.2.3 specification.
 *
 * alarm_id:  The identifier of the alarm
 * start:  Absolute value in ticks.
 * cycle:  Cycle value in case of a cyclic alarm. In case of a one shot
 *         alarm, cycle shall be zero
 *
 * Return value:
 * E_OK:        No error (Standard & Extended)
 * E_OS_NOFUNC: Alarm <alarm_id> is already in use (Standard & Extended)
 * E_OS_ID:     <alarm_id> is invalid (Extended)
 * E_OS_VALUE:  <start> out of bounds (Extended)
 * E_OS_VALUE:  <cycle> out of bounds (Extended)
 */
FUNC(StatusType, OS_CODE) SetAbsAlarm(CONST(AlarmType, AUTOMATIC) alarm_id,CONST(TickType, AUTOMATIC) start,CONST(TickType, AUTOMATIC) cycle)
{
  
  slow_task( (void*) &alarm_id, (void*) &start, (void*) &cycle,OSServiceId_SetAbsAlarm);

  StatusType res = tpl_set_abs_alarm_service(alarm_id, start, cycle);

  compute_NEFT( (void*) &alarm_id, (void*) &start, (void*) &cycle,OSServiceId_SetAbsAlarm);
  
  
  return res;
  
}

/*
 * CancelAlarm
 *
 * CancelAlarm cancels a started alarm.
 * See page 65 of the OSEK OS 2.2.3 specification.
 *
 * alarm_id:  The identifier of the alarm
 *
 * Return value:
 * E_OK:        No error (Standard & Extended)
 * E_OS_NOFUNC: Alarm <alarm_id> is not in use (Standard & Extended)
 * E_OS_ID:     <alarm_id> is invalid (Extended)
 */
FUNC(StatusType, OS_CODE) CancelAlarm(CONST(AlarmType, AUTOMATIC) alarm_id)
{
  
  slow_task( (void*) &alarm_id,NULL,NULL,OSServiceId_CancelAlarm);

  StatusType res = tpl_cancel_alarm_service(alarm_id);

  compute_NEFT( (void*) &alarm_id,NULL,NULL,OSServiceId_CancelAlarm);
  
  
  return res;
  
}


/* End of file tpl_os.c */
